# Name:- Shital Ashok Gaikwad

## Data Analysis on Invistico Airlines.

In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv(r"C:\Users\ARJUN SALUNKHE\Downloads\Invistico_Airline.csv")
dataset

,satisfaction,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,...,Online support,Ease of Online booking,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes
0,satisfied,Female,Loyal Customer,65,Personal Travel,Eco,265,0,0,0,...,2,3,3,0,3,5,3,2,0,0.0
1,satisfied,Male,Loyal Customer,47,Personal Travel,Business,2464,0,0,0,...,2,3,4,4,4,2,3,2,310,305.0
2,satisfied,Female,Loyal Customer,15,Personal Travel,Eco,2138,0,0,0,...,2,2,3,3,4,4,4,2,0,0.0
3,satisfied,Female,Loyal Customer,60,Personal Travel,Eco,623,0,0,0,...,3,1,1,0,1,4,1,3,0,0.0
4,satisfied,Female,Loyal Customer,70,Personal Travel,Eco,354,0,0,0,...,4,2,2,0,2,4,2,5,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129875,satisfied,Female,disloyal Customer,29,Personal Travel,Eco,1731,5,5,5,...,2,2,3,3,4,4,4,2,0,0.0
129876,dissatisfied,Male,disloyal Customer,63,Personal Travel,Business,2087,2,3,2,...,1,3,2,3,3,1,2,1,174,172.0
129877,dissatisfied,Male,disloyal Customer,69,Personal Travel,Eco,2320,3,0,3,...,2,4,4,3,4,2,3,2,155,163.0
129878,dissatisfied,Male,disloyal Customer,66,Personal Travel,Eco,2450,3,2,3,...,2,3,3,2,3,2,1,2,193,205.0
129879,dissatisfied,Female,disloyal Customer,38,Personal Travel,Eco,4307,3,4,3,...,3,4,5,5,5,3,3,3,185,186.0

## No. of rows and columns

In [3]:
rows=len(dataset.axes[0])
rows

129880

In [4]:
columns=len(dataset.axes[1])
columns

23

In [5]:
print("Number of rows in dataset: ",rows)
print("Number of columns in dataset: ",columns)

Number of rows in dataset:  129880
Number of columns in dataset:  23

## Null analysis

In [6]:
dataset.isnull().any()

satisfaction                         False
Gender                               False
Customer Type                        False
Age                                  False
Type of Travel                       False
Class                                False
Flight Distance                      False
Seat comfort                         False
Departure/Arrival time convenient    False
Food and drink                       False
Gate location                        False
Inflight wifi service                False
Inflight entertainment               False
Online support                       False
Ease of Online booking               False
On-board service                     False
Leg room service                     False
Baggage handling                     False
Checkin service                      False
Cleanliness                          False
Online boarding                      False
Departure Delay in Minutes           False
Arrival Delay in Minutes              True
dtype: bool

In [7]:
dataset.isnull().sum()

satisfaction                           0
Gender                                 0
Customer Type                          0
Age                                    0
Type of Travel                         0
Class                                  0
Flight Distance                        0
Seat comfort                           0
Departure/Arrival time convenient      0
Food and drink                         0
Gate location                          0
Inflight wifi service                  0
Inflight entertainment                 0
Online support                         0
Ease of Online booking                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Cleanliness                            0
Online boarding                        0
Departure Delay in Minutes             0
Arrival Delay in Minutes             393
dtype: int64

## Duplicated Items in all over dataset

In [8]:
duplicate=dataset.duplicated().sum()
duplicate

0

## EDA of total count of satisfied v\s unsatisfied response

In [9]:
count=dataset["satisfaction"].value_counts()
count

satisfied       71087
dissatisfied    58793
Name: satisfaction, dtype: int64

## Correlation amongst variables (customer satisfaction column)

In [10]:
from sklearn.preprocessing import LabelEncoder
l1=LabelEncoder()
dataset["satisfaction"]=l1.fit_transform(dataset["satisfaction"])

In [11]:
dataset

,satisfaction,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,...,Online support,Ease of Online booking,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes
0,1,Female,Loyal Customer,65,Personal Travel,Eco,265,0,0,0,...,2,3,3,0,3,5,3,2,0,0.0
1,1,Male,Loyal Customer,47,Personal Travel,Business,2464,0,0,0,...,2,3,4,4,4,2,3,2,310,305.0
2,1,Female,Loyal Customer,15,Personal Travel,Eco,2138,0,0,0,...,2,2,3,3,4,4,4,2,0,0.0
3,1,Female,Loyal Customer,60,Personal Travel,Eco,623,0,0,0,...,3,1,1,0,1,4,1,3,0,0.0
4,1,Female,Loyal Customer,70,Personal Travel,Eco,354,0,0,0,...,4,2,2,0,2,4,2,5,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129875,1,Female,disloyal Customer,29,Personal Travel,Eco,1731,5,5,5,...,2,2,3,3,4,4,4,2,0,0.0
129876,0,Male,disloyal Customer,63,Personal Travel,Business,2087,2,3,2,...,1,3,2,3,3,1,2,1,174,172.0
129877,0,Male,disloyal Customer,69,Personal Travel,Eco,2320,3,0,3,...,2,4,4,3,4,2,3,2,155,163.0
129878,0,Male,disloyal Customer,66,Personal Travel,Eco,2450,3,2,3,...,2,3,3,2,3,2,1,2,193,205.0
129879,0,Female,disloyal Customer,38,Personal Travel,Eco,4307,3,4,3,...,3,4,5,5,5,3,3,3,185,186.0

In [12]:
cor=dataset.corr()
cor

,satisfaction,Age,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,Gate location,Inflight wifi service,Inflight entertainment,Online support,Ease of Online booking,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes
satisfaction,1.000000,0.117971,-0.039224,0.242384,-0.015507,0.120677,-0.012071,0.227062,0.523496,0.390143,0.431772,0.352047,0.304928,0.260347,0.266179,0.259330,0.338147,-0.073909,-0.080691
Age,0.117971,1.000000,-0.249625,0.008784,0.039055,0.015749,-0.000547,0.013965,0.130511,0.121201,0.071594,0.066704,0.083762,-0.015452,0.031845,-0.018271,0.037973,-0.009041,-0.011248
Flight Distance,-0.039224,-0.249625,1.000000,-0.042409,0.001350,-0.004649,-0.002409,0.012230,-0.027542,-0.032022,-0.022299,-0.032559,-0.030316,0.019768,0.002456,0.009432,0.009604,0.112555,0.110103
Seat comfort,0.242384,0.008784,-0.042409,1.000000,0.434951,0.715997,0.405300,0.129131,0.426447,0.120278,0.211531,0.121149,0.136136,0.118489,0.041214,0.108475,0.130396,-0.023817,-0.025506
Departure/Arrival time convenient,-0.015507,0.039055,0.001350,0.434951,1.000000,0.527381,0.544259,-0.001974,0.077203,-0.000546,0.001755,0.060446,0.029422,0.067396,0.062794,0.067126,-0.000623,0.004395,0.002599
Food and drink,0.120677,0.015749,-0.004649,0.715997,0.527381,1.000000,0.523328,0.025917,0.367669,0.028554,0.041189,0.038646,0.074161,0.036370,0.011898,0.033416,0.013587,-0.013433,-0.014881
Gate location,-0.012071,-0.000547,-0.002409,0.405300,0.544259,0.523328,1.000000,-0.004086,-0.000280,0.002908,0.001442,-0.025132,-0.007407,-0.000401,-0.031859,-0.001705,-0.003043,0.003962,0.003640
Inflight wifi service,0.227062,0.013965,0.012230,0.129131,-0.001974,0.025917,-0.004086,1.000000,0.253823,0.557340,0.601100,0.060794,0.033589,0.038251,0.092508,0.038263,0.631786,-0.032900,-0.035270
Inflight entertainment,0.523496,0.130511,-0.027542,0.426447,0.077203,0.367669,-0.000280,0.253823,1.000000,0.441957,0.321731,0.183912,0.160731,0.117213,0.224120,0.109451,0.355714,-0.030491,-0.033321
Online support,0.390143,0.121201,-0.032022,0.120278,-0.000546,0.028554,0.002908,0.557340,0.441957,1.000000,0.617489,0.157930,0.138433,0.102444,0.206824,0.095726,0.669843,-0.034018,-0.036087
Ease of Online booking,0.431772,0.071594,-0.022299,0.211531,0.001755,0.041189,0.001442,0.601100,0.321731,0.617489,1.000000,0.436264,0.355122,0.398322,0.137744,0.417675,0.684320,-0.036545,-0.039806
On-board service,0.352047,0.066704,-0.032559,0.121149,0.060446,0.038646,-0.025132,0.060794,0.183912,0.157930,0.436264,1.000000,0.411746,0.530448,0.250839,0.551294,0.139506,-0.037641,-0.041456
Leg room service,0.304928,0.083762,-0.030316,0.136136,0.029422,0.074161,-0.007407,0.033589,0.160731,0.138433,0.355122,0.411746,1.000000,0.411640,0.167942,0.411505,0.112900,0.003660,0.000472
Baggage handling,0.260347,-0.015452,0.019768,0.118489,0.067396,0.036370,-0.000401,0.038251,0.117213,0.102444,0.398322,0.530448,0.411640,1.000000,0.240858,0.631803,0.111920,-0.009985,-0.014164
Checkin service,0.266179,0.031845,0.002456,0.041214,0.062794,0.011898,-0.031859,0.092508,0.224120,0.206824,0.137744,0.250839,0.167942,0.240858,1.000000,0.241734,0.184344,-0.020896,-0.023860
Cleanliness,0.259330,-0.018271,0.009432,0.108475,0.067126,0.033416,-0.001705,0.038263,0.109451,0.095726,0.417675,0.551294,0.411505,0.631803,0.241734,1.000000,0.106238,-0.062134,-0.067208
Online boarding,0.338147,0.037973,0.009604,0.130396,-0.000623,0.013587,-0.003043,0.631786,0.355714,0.669843,0.684320,0.139506,0.112900,0.111920,0.184344,0.106238,1.000000,-0.020045,-0.021784
Departure Delay in Minutes,-0.073909,-0.009041,0.112555,-0.023817,0.004395,-0.013433,0.003962,-0.032900,-0.030491,-0.034018,-0.036545,-0.037641,0.003660,-0.009985,-0.020896,-0.062134,-0.020045,1.000000,0.965291
Arrival Delay in Minutes,-0.080691,-0.011248,0.110103,-0.025506,0.002599,-0.014881,0.003640,-0.035270,-0.033321,-0.036087,-0.039806,-0.041456,0.000472,-0.014164,-0.023860,-0.067208,-0.021784,0.965291,1.000000

## EDA of total counts of satisfied or unsatisfied responses based on 
## 1) Gender

In [13]:
data=pd.read_csv(r"C:\Users\ARJUN SALUNKHE\Downloads\Invistico_Airline.csv")
data

,satisfaction,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,...,Online support,Ease of Online booking,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes
0,satisfied,Female,Loyal Customer,65,Personal Travel,Eco,265,0,0,0,...,2,3,3,0,3,5,3,2,0,0.0
1,satisfied,Male,Loyal Customer,47,Personal Travel,Business,2464,0,0,0,...,2,3,4,4,4,2,3,2,310,305.0
2,satisfied,Female,Loyal Customer,15,Personal Travel,Eco,2138,0,0,0,...,2,2,3,3,4,4,4,2,0,0.0
3,satisfied,Female,Loyal Customer,60,Personal Travel,Eco,623,0,0,0,...,3,1,1,0,1,4,1,3,0,0.0
4,satisfied,Female,Loyal Customer,70,Personal Travel,Eco,354,0,0,0,...,4,2,2,0,2,4,2,5,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129875,satisfied,Female,disloyal Customer,29,Personal Travel,Eco,1731,5,5,5,...,2,2,3,3,4,4,4,2,0,0.0
129876,dissatisfied,Male,disloyal Customer,63,Personal Travel,Business,2087,2,3,2,...,1,3,2,3,3,1,2,1,174,172.0
129877,dissatisfied,Male,disloyal Customer,69,Personal Travel,Eco,2320,3,0,3,...,2,4,4,3,4,2,3,2,155,163.0
129878,dissatisfied,Male,disloyal Customer,66,Personal Travel,Eco,2450,3,2,3,...,2,3,3,2,3,2,1,2,193,205.0
129879,dissatisfied,Female,disloyal Customer,38,Personal Travel,Eco,4307,3,4,3,...,3,4,5,5,5,3,3,3,185,186.0

In [22]:
x1=data.iloc[:,[0,1]]

In [23]:
x1.pivot_table(index=["satisfaction","Gender"],aggfunc=len)

satisfaction  Gender
dissatisfied  Female    22971
              Male      35822
satisfied     Female    42928
              Male      28159
dtype: int64

# 2)Customer Type

In [26]:
x2=data.iloc[:,[0,2]]

In [28]:
x2.pivot_table(index=["satisfaction","Customer Type"],aggfunc=len)

satisfaction  Customer Type
dissatisfied  Loyal Customer       40713
              disloyal Customer    18080
satisfied     Loyal Customer       65387
              disloyal Customer     5700
dtype: int64

# 3)Age

In [15]:
#We consider here the age_group between
#Child==0-15
#Teenage==15-30
#Adult==30-50
#Oldage==50+ above

In [16]:
Age_data=[]
for x in data["Age"]:
    if 0<x<=15:
        Age_data.append("Child")
    elif 15<x<=30:
        Age_data.append("Teenage")
    elif 30<x<=50:
        Age_data.append("Adult")
    else:
        Age_data.append("Oldage")

In [17]:
data["Age_data"]=Age_data

In [18]:
data

,satisfaction,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,...,Ease of Online booking,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes,Age_data
0,satisfied,Female,Loyal Customer,65,Personal Travel,Eco,265,0,0,0,...,3,3,0,3,5,3,2,0,0.0,Oldage
1,satisfied,Male,Loyal Customer,47,Personal Travel,Business,2464,0,0,0,...,3,4,4,4,2,3,2,310,305.0,Adult
2,satisfied,Female,Loyal Customer,15,Personal Travel,Eco,2138,0,0,0,...,2,3,3,4,4,4,2,0,0.0,Child
3,satisfied,Female,Loyal Customer,60,Personal Travel,Eco,623,0,0,0,...,1,1,0,1,4,1,3,0,0.0,Oldage
4,satisfied,Female,Loyal Customer,70,Personal Travel,Eco,354,0,0,0,...,2,2,0,2,4,2,5,0,0.0,Oldage
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129875,satisfied,Female,disloyal Customer,29,Personal Travel,Eco,1731,5,5,5,...,2,3,3,4,4,4,2,0,0.0,Teenage
129876,dissatisfied,Male,disloyal Customer,63,Personal Travel,Business,2087,2,3,2,...,3,2,3,3,1,2,1,174,172.0,Oldage
129877,dissatisfied,Male,disloyal Customer,69,Personal Travel,Eco,2320,3,0,3,...,4,4,3,4,2,3,2,155,163.0,Oldage
129878,dissatisfied,Male,disloyal Customer,66,Personal Travel,Eco,2450,3,2,3,...,3,3,2,3,2,1,2,193,205.0,Oldage
129879,dissatisfied,Female,disloyal Customer,38,Personal Travel,Eco,4307,3,4,3,...,4,5,5,5,3,3,3,185,186.0,Adult

In [19]:
x=data.iloc[:,[0,-1]]

In [20]:
x

        satisfaction Age_data
0          satisfied   Oldage
1          satisfied    Adult
2          satisfied    Child
3          satisfied   Oldage
4          satisfied   Oldage
...              ...      ...
129875     satisfied  Teenage
129876  dissatisfied   Oldage
129877  dissatisfied   Oldage
129878  dissatisfied   Oldage
129879  dissatisfied    Adult

[129880 rows x 2 columns]

In [21]:
x.pivot_table(index=["satisfaction","Age_data"],aggfunc=len)

satisfaction  Age_data
dissatisfied  Adult       22619
              Child        4273
              Oldage      13445
              Teenage     18456
satisfied     Adult       32779
              Child        3193
              Oldage      20157
              Teenage     14958
dtype: int64

# 4) Type of travel

In [29]:
x3=data.iloc[:,[0,4]]
x3.pivot_table(index=["satisfaction","Type of Travel"],aggfunc=len)

satisfaction  Type of Travel
dissatisfied  Business travel    37337
              Personal Travel    21456
satisfied     Business travel    52356
              Personal Travel    18731
dtype: int64

# 5) Class

In [35]:
x4=data.iloc[:,[0,5]]

In [36]:
x4.pivot_table(index=["satisfaction","Class"],aggfunc=len)

satisfaction  Class
dissatisfied  Business    18065
              Eco         35336
              Eco Plus     5392
satisfied     Business    44095
              Eco         22973
              Eco Plus     4019
dtype: int64

# 6)Flight Distance

In [38]:
x5=data.iloc[:,[0,6]]

In [39]:
x5.pivot_table(index=["satisfaction","Flight Distance"],aggfunc=len)

satisfaction  Flight Distance
dissatisfied  50                 4
              51                 6
              52                 2
              53                 6
              54                 6
                                ..
satisfied     6828               1
              6868               1
              6907               1
              6948               1
              6950               1
Length: 9950, dtype: int64

# 7)Seat comfort

In [41]:
x6=data.iloc[:,[0,7]]

In [42]:
x6.pivot_table(index=["satisfaction","Seat comfort"],aggfunc=len)

satisfaction  Seat comfort
dissatisfied  0                  10
              1               11503
              2               18454
              3               18794
              4                9891
              5                 141
satisfied     0                4787
              1                9446
              2               10272
              3               10389
              4               18507
              5               17686
dtype: int64